baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Oliver Mills"
theme = "hyde"
googleAnalytics = "UA-134759200-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Posts"
    url = "/post/"
[[menu.contact]]
    name = "LinkedIn"
    url = "https://nz.linkedin.com/in/oliver-mills-a2238559"
[[menu.contact]]
    name = "Email"
    url = "mailto:olivarski@gmail.com"
[[menu.contact]]
    name = "GitHub"
    url = "https://github.com/olivermills"

[author]
    image = 'me.jpg'

[params]
    description = "A personal website built through Hugo and blogdown (R Studio)."
    # Change contactHeader text
    # Or comment out to use <hr> instead
    contactHeader = "Contact Me"

    # Change Hyde theme
    themeColor = "theme-base-0d"
    # Overide or add custom CSS styles
    #customCSS = "/css/custom.css"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
